VALID_COLUMNS = {
    "planilla_validadora": [
        "CODIGO_ESTABLECIMIENTO",
        "NOMBRE_ESTABLECIMIENTO",
        "ANIO",
        "MES",
        "RUT",
        "NOMBRE",
        "APELLIDO_PATERNO",
        "APELLIDO_MATERNO",
        "FECHA_NACIMIENTO",
        "CARGO",
        "FUNCION",
        "GRUPO",
        "NIVEL_ATENCION",
        "FECHA_INGRESO_SISTEMA_ESCOLAR",
        "ANIOS_SERVICIO_CON_EMPLEADOR",
        "FECHA_ESTABLECIDA_CONTRATO",
        "JORNADA_HORAS",
        "PLAZO_CONTRATO",
        "TIPO_CONTRATO",
        "NIVEL_EDUCACIONAL",
        "TITULO",
        "INSTITUCION_ACADEMICA",
        "DIAS_LICENCIA_MEDICA",
        "DIAS_SIN_GOCE_SUELDO",
        "TOTAL_DIAS_TRABAJADOS",
        "TOTAL_DIAS_PAGADOS",
        "REMUNERACIONES_INCLUYE_BONOS_Y_ASIGNACIONES_PACTADAS",
        "MOVILIZACION_MAS_COLACION",
        "MES_Y_ANIO_INICIO_PAGO",
        "ASIGNACION_MENSUAL_SOLICITADA_DE_CD",
        "SUELDO_BASE",
        "HORAS_EXTRAS",
        "ANTIGUEDAD_BIENIOS",
        "INCENTIVO",
        "ASIGNACION_RESPONSABILIDAD",
        "RELIQUIDACIONES",
        "INCREMENTOS_JUNJI",
        "AGUINALDO",
        "ASIGNACION_ZONA_EXTREMA",
        "BONO",
        "OTROS_AJUSTES",
        "ESPECIFIQUE",
        "BONO_VACACIONES_FISCAL",
        "BONO_TERMINO_CONFLICTO_FISCAL",
        "AGUINALDO_2",
        "BONO_ESCOLAR",
        "MOVILIZACION",
        "BONO_2",
        "COLACION",
        "ASIGNACIONES_FAMILIARES",
        "ASIGNACION_LEY_20905",
        "OTROS_AJUSTES_2",
        "ESPECIFIQUE_2",
        "ASIGNACION_CARRERA_DOCENTE_PAGADA",
        "SUELDO_BRUTO_O_TOTAL_HABERES",
        "OBSERVACIONES",
    ],
    "macro": ["region", "codigo", "tipo", "cantidad"],
}

VALID_TYPES = {
    "planilla_validadora": {
        "CODIGO_ESTABLECIMIENTO": "numerico",
        "ANIO": "numerico",
        "MES": "numerico",
        "RUT": "texto",
        "NOMBRE": "texto",
        "APELLIDO_PATERNO": "texto",
        "APELLIDO_MATERNO": "texto",
        "FECHA_NACIMIENTO": "fecha",
        "CARGO": "texto",
        "FUNCION": "texto",
        "GRUPO": "texto",
        "NIVEL_ATENCION": "texto",
        "FECHA_INGRESO_SISTEMA_ESCOLAR": "fecha",
        "ANIOS_SERVICIO_CON_EMPLEADOR": "numerico",
        "FECHA_ESTABLECIDA_CONTRATO": "fecha",
        "JORNADA_HORAS": "numerico",
        "PLAZO_CONTRATO": "texto",
        "TIPO_CONTRATO": "texto",
        "NIVEL_EDUCACIONAL": "texto",
        "TITULO": "texto",
        "INSTITUCION_ACADEMICA": "texto",
        "DIAS_LICENCIA_MEDICA": "numerico",
        "DIAS_SIN_GOCE_SUELDO": "numerico",
        "TOTAL_DIAS_TRABAJADOS": "numerico",
        "TOTAL_DIAS_PAGADOS": "numerico",
        "REMUNERACIONES_INCLUYE_BONOS_Y_ASIGNACIONES_PACTADAS": "numerico",
        "MOVILIZACION_MAS_COLACION": "numerico",
        "MES_Y_ANIO_INICIO_PAGO": "fecha",
        "ASIGNACION_MENSUAL_SOLICITADA_DE_CD": "numerico",
        "SUELDO_BASE": "numerico",
        "HORAS_EXTRAS": "numerico",
        "ANTIGUEDAD_BIENIOS": "numerico",
        "INCENTIVO": "numerico",
        "ASIGNACION_RESPONSABILIDAD": "numerico",
        "RELIQUIDACIONES": "numerico",
        "INCREMENTOS_JUNJI": "numerico",
        "AGUINALDO": "numerico",
        "ASIGNACION_ZONA_EXTREMA": "numerico",
        "BONO": "numerico",
        "OTROS_AJUSTES": "numerico",
        "ESPECIFIQUE": "texto",
        "BONO_VACACIONES_FISCAL": "numerico",
        "BONO_TERMINO_CONFLICTO_FISCAL": "numerico",
        "AGUINALDO_2": "numerico",
        "BONO_ESCOLAR": "numerico",
        "MOVILIZACION": "numerico",
        "BONO_2": "numerico",
        "COLACION": "numerico",
        "ASIGNACIONES_FAMILIARES": "numerico",
        "ASIGNACION_LEY_20905": "numerico",
        "OTROS_AJUSTES_2": "numerico",
        "ESPECIFIQUE_2": "texto",
        "ASIGNACION_CARRERA_DOCENTE_PAGADA": "numerico",
        "SUELDO_BRUTO_O_TOTAL_HABERES": "numerico",
        "OBSERVACIONES": "texto",
    }
}

VALID_RANGES = {
    "planilla_validadora": {
        "CODIGO_ESTABLECIMIENTO": (1_000_000, 16_999_999),
        "ANIO": (2013, 2030),
        "MES": (1, 12),
        "GRUPO": (1, 11),
        "FECHA_NACIMIENTO": ("1950-01-01", "2010-12-31"),
        "ANIOS_SERVICIO_CON_EMPLEADOR": (0, 100),
        "JORNADA_HORAS": (0, 44),
        "DIAS_LICENCIA_MEDICA": (0, 30),
        "DIAS_SIN_GOCE_SUELDO": (0, 30),
        "TOTAL_DIAS_TRABAJADOS": (0, 30),
        "TOTAL_DIAS_PAGADOS": (0, 30),
    }
}

VALID_VALUES = {
    "planilla_validadora": {
        "CARGO": {
            "allowed": [
                "administrativo",
                "auxiliar",
                "tecnico",
                "educadora",
                "directora",
            ],
        },
        "NIVEL_ATENCION": {
            "allowed": ["sala cuna", "medio menor", "medio mayor", "transicion"],
        },
        "PLAZO_CONTRATO": {
            "allowed": ["plazo fijo", "indefinido"],
        },
        "TIPO_CONTRATO": {
            "allowed": ["codigo del trabajo", "estatuto administrativo"],
        },
    }
}

COLUMNS_ALLOW_EMPTY = {
    "planilla_validadora": {
        "APELLIDO_MATERNO": True,
        "OBSERVACIONES": True,
        "ESPECIFIQUE": True,
        "ESPECIFIQUE_2": True,
    }
}
